theme: jekyll-theme-minimal
title: Christopher D. Higgins
logo: /assets/img/bio.jpg
description: Assistant Professor<br/>Department of Human Geography<br/>University of Toronto Scarborough
google_analytics: UA-126124472-1
navigation:
  - title: Home
    url: /
  - title: Projects and Openings
    url: research
  - title: Publications
    url: publications
  - title: Teaching
    url: teaching
  - title: Contact
    url: contact
