theme: jekyll-theme-minimal
title: Christopher D. Higgins
description: Assistant Professor, the Hong Kong Polytechnic University
navigation:
  - title: Home
    url: /
  - title: Research
    url: research
