project:
  type: website
  output-dir: docs

website:
  title: "Christopher D. Higgins"
  site-url: https://higgicd.github.io
  repo-url: https://github.com/higgicd/higgicd.github.io
  open-graph: true
  twitter-card:
    creator: "@higgicd"
    card-style: summary_large_image
  navbar:
    background: light
    title: false
    right:
      #- about.qmd
      #- icon: twitter
      #  aria-label: twitter
      #  href: https://twitter.com/higgicd
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/higgicd/
      - icon: square-fill
        aria-label: bluesky
        href: https://bsky.app/profile/higgicd.bsky.social
      - icon: mortarboard-fill
        aria-label: scholar
        href: https://scholar.google.ca/citations?user=BvBZbXMAAAAJ
      - icon: github
        aria-label: github
        href: https://github.com/higgicd
    left:
      - href: index.qmd
        text: Home
      #- about.qmd
      - publications.qmd
      - teaching.qmd

format:
  html:
    theme: 
      light: cosmo
    css: styles.css
    toc: true

editor: visual

